services:
  web:
    build: 
      context: /root/aws-infrastructure/django-aws
      dockerfile: /root/aws-infrastructure/django-aws/django-aws-backend/Dockerfile
    command: gunicorn django_aws.wsgi:application --bind 0.0.0.0:80
    volumes:
        - .:/code
    # env_file:
    #     - ./.env
    ports:
        - 80:80
    depends_on:
        - db
        - sqs
  sqs:
    image: "softwaremill/elasticmq-native:latest"
    ports:
      - "9324:9324"
      - "9325:9325"
  db:
    image: "postgres:14.2"
    ports:
      - 5432:5432
    volumes:
            - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_aws"

volumes:
  postgres_data: