services:
  skipify:
    build: 
      context: /root/aws-infrastructure/django-aws
      dockerfile: /root/aws-infrastructure/django-aws/django-aws-backend/Dockerfile
    container_name: "skipify"
    command: gunicorn django_aws.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    restart: "unless-stopped"
    depends_on:
        - db
        - sqs
  celery:
    build: 
      context: /root/aws-infrastructure/django-aws
      dockerfile: /root/aws-infrastructure/django-aws/django-aws-backend/Dockerfile
    command: celery -A django_aws worker --loglevel=info -B
    container_name: "celery"
    volumes:
      - .:/code
    restart: "unless-stopped"
    env_file:
      - ./.env
    depends_on:
      - db
      - sqs
      - skipify
  sqs:
    image: "softwaremill/elasticmq-native:latest"
    restart: "unless-stopped"
    container_name: "sqs"
    ports:
      - 9324:9324
      - 9325:9325
  db:
    image: "postgres:14.2"
    container_name: "db"
    restart: "unless-stopped"
    expose:
      - 5432
    volumes:
            - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_aws"

volumes:
  postgres_data: