services:
  web:
    build: .
    command: gunicorn django-aws.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - .:/code
    # env_file:
    #     - ./.env
    ports:
        - 8000:8000
    depends_on:
        - db
        # - redis
  db:
    image: "postgres:14.2"
    ports:
      - 5432:5432
    volumes:
            - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_aws"

volumes:
  postgres_data: