# Generated by Django 5.0.4 on 2025-03-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tasklock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklock',
            old_name='updated_at',
            new_name='locked_at',
        ),
    ]
