# Generated by Django 5.0.4 on 2025-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_updated_at_tasklock_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasklock',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
