# Generated by Django 5.0.4 on 2025-03-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tasklock_updated_at_alter_tasklock_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklock',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
