name: Build and Deploy
run-name: Build and Deploy container to ECS ${{ github.actor }}
on:
  push:
    branches:
      - main

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout

jobs:
  deploy_infra:
    name: Create Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: ezequielmartell/skipify-aws-infrastructure

    - name: Deploy Infrastructure
      uses: ezequielmartell/skipify-aws-infrastructure/.github/workflows/deploy_infra.yml@main
      with:
        sha: ${{ github.sha }}

  build:
      name: Build and Push
      runs-on: ubuntu-latest
      steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: django-aws-backend
        run: |
          echo "############################################"
          echo "#######        Building Image         ######"
          echo "############################################"
          docker build -t $REGISTRY/$REPOSITORY .
          echo "############################################"
          echo "#######  Pushing image to Amazon ECR  ######"
          echo "############################################"
          docker push $REGISTRY/$REPOSITORY
  deploy:
    name: Create Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
          with:
            role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
            aws-region: us-east-2
        - run: |
            echo "Creating deployment for Backend Service"
            aws deploy create-deployment --cli-input-yaml file://codedeploy/appspec.yaml
         # need to add something here that bounces the beat and worker services