name: Build and Deploy
run-name: Build and Deploy container to ECS ${{ github.actor }}
on:
  push:
    branches:
      - main

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout

jobs:
  
  gather_secrets:
    name: Gather Secrets
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Step name
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            TF_VAR_prod_rds_password, TF-VAR-prod-rds-password
            TF_VAR_prod_backend_secret_key, TF-VAR-prod-backend-secret-key
            TF_VAR_prod_sendgrid_api_key, TF-VAR-prod-sendgrid-api-key
            TF_VAR_prod_client_id, TF-VAR-prod-client-id
            TF_VAR_prod_client_secret, TF-VAR-prod-client-secret
            TF_VAR_prod_redirect_uri, TF-VAR-prod-redirect-uri

  deploy_infra:
    needs: gather_secrets
    uses: ezequielmartell/skipify-aws-infrastructure/.github/workflows/deploy_infra.yml@main
    with:
      sha: ${{ github.sha }}

  build:
      name: Build and Push
      runs-on: ubuntu-latest
      needs: deploy_infra
      steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: django-aws-backend
        run: |
          echo "############################################"
          echo "#######        Building Image         ######"
          echo "############################################"
          docker build -t $REGISTRY/$REPOSITORY .
          echo "############################################"
          echo "#######  Pushing image to Amazon ECR  ######"
          echo "############################################"
          docker push $REGISTRY/$REPOSITORY
  deploy:
    name: Create Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
          with:
            role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
            aws-region: us-east-2
        - run: |
            echo "Creating deployment for Backend Service"
            aws deploy create-deployment --cli-input-yaml file://codedeploy/appspec.yaml
         # need to add something here that bounces the beat and worker services