name: Build and Deploy
run-name: Build and Deploy container to ECS ${{ github.actor }}
on:
  push:
    branches:
      - main

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout

jobs:
  deploy_infra:
    name: Trigger Infrastructure Deployment Workflow
    uses: ezequielmartell/skipify-aws-infrastructure/.github/workflows/deploy_infra.yml@main
    with:
      sha: ${{ github.sha }}
      type: "backend"

  build:
      name: Build and Push
      runs-on: ubuntu-latest
      needs: deploy_infra
      steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: django-aws-backend
          SHA: ${{ github.sha }}
        run: |
          echo "############################################"
          echo "#######        Building Image         ######"
          echo "############################################"
          docker build -t $REGISTRY/$REPOSITORY:$SHA .
          echo "############################################"
          echo "#######  Pushing image to Amazon ECR  ######"
          echo "############################################"
          docker push $REGISTRY/$REPOSITORY:$SHA

  deploy:
    name: Create Deployment
    runs-on: ubuntu-latest
    needs: 
      - build
      - deploy_infra
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
          with:
            role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
            aws-region: us-east-2
        - name: CLI Deployment
          run: |
            echo "Creating deployment for backend service."
            aws deploy create-deployment --cli-input-json '{"applicationName":"backend_deployment","deploymentGroupName":"backend-deploy-group","revision":{"revisionType":"AppSpecContent","appSpecContent":{"content":"{\"version\":0.0,\"Resources\":[{\"TargetService\":{\"Type\":\"AWS::ECS::Service\",\"Properties\":{\"TaskDefinition\":\"'${{ needs.deploy_infra.outputs.task_def_arn }}'\",\"LoadBalancerInfo\":{\"ContainerName\":\"prod-backend-web\",\"ContainerPort\":8000}}}}]}"}}}'           
        # need to add something here that bounces the beat and worker services